require('dotenv').config();

module.exports = {
  secretKey: process.env.SECRET_KEY || 'THISISMYSECURETOKEN',
  host: process.env.HOST || 'http://localhost',
  port: process.env.PORT || 21465,
  startAllSession: process.env.START_ALL_SESSION || true,
  tokenStoreType: process.env.TOKEN_STORE_TYPE || 'file',
  webhook: {
    url: process.env.WEBHOOK_URL || null,
    autoDownload: process.env.WEBHOOK_AUTO_DOWNLOAD || true,
    uploadS3: process.env.WEBHOOK_UPLOAD_S3 || false,
    readMessage: process.env.WEBHOOK_READ_MESSAGE || true,
    allUnreadOnStart: process.env.WEBHOOK_ALL_UNREAD_ON_START || false,
    listenAcks: process.env.WEBHOOK_LISTEN_ACKS || true,
    onPresenceChanged: process.env.WEBHOOK_ON_PRESENCE_CHANGED || true,
    onParticipantsChanged: process.env.WEBHOOK_ON_PARTICIPANTS_CHANGED || true,
  },
  archive: {
    enable: process.env.ARCHIVE_ENABLE || false,
    waitTime: process.env.ARCHIVE_WAIT_TIME || 10,
    daysToArchive: process.env.ARCHIVE_DAYS_TO_ARCHIVE || 45,
  },
  log: {
    level: process.env.LOG_LEVEL || 'error',
    logger: ['console', 'file'],
  },
  createOptions: {
    browserArgs: [
      '--disable-setuid-sandbox',
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
    ],
  },
  mapper: {
    enable: process.env.MAPPER_ENABLE || false,
    prefix: process.env.MAPPER_PREFIX || 'tagone-',
  },
  db: {
    mongodbDatabase: process.env.DB_MONGODB_DATABASE || 'tokens',
    mongodbCollection: process.env.DB_MONGODB_COLLECTION || null,
    mongodbUser: process.env.DB_MONGODB_USER || null,
    mongodbPassword: process.env.DB_MONGODB_PASSWORD || null,
    mongodbHost: process.env.DB_MONGODB_HOST || null,
    mongoIsRemote: process.env.DB_MONGODB_IS_REMOTE || true,
    mongoURLRemote: process.env.DB_MONGODB_URL_REMOTE || null,
    mongodbPort: process.env.DB_MONGODB_PORT || 27017,
    redisFullHost: process.env.DB_REDIS_FULL_HOST || null,
    redisHost: process.env.DB_REDIS_HOST || 'localhost',
    redisPort: process.env.DB_REDIS_PORT || 6379,
    redisPassword: process.env.DB_REDIS_PASSWORD || null,
    redisDb: process.env.DB_REDIS_DB || 0,
    redisPrefix: process.env.DB_REDIS_PREFIX || "docker"
  },
};
